import 'package:atlas/features/prices/domain/models/price_observation.dart';

/// Observations vérifiées pour les tests uniquement — jamais utilisées en prod.
abstract final class PriceIntelligenceFixtures {
  static final updatedAt = DateTime(2026, 7, 1);

  static final sample = <PriceObservation>[
    PriceObservation(
      id: 'sp95-marrakech',
      itemName: 'SP95 Marrakech',
      category: PriceIntelligenceCategory.fuel,
      cityName: 'Marrakech',
      unitLabel: 'litre',
      currentAmountMad: 12.45,
      minAmountMad: 12.20,
      avgAmountMad: 12.40,
      maxAmountMad: 12.70,
      lastUpdatedAt: updatedAt,
      source: 'Station agrégée Atlas (test)',
      confidence: PriceConfidence.high,
      verificationStatus: PriceVerificationStatus.verified,
      userReportsCount: 3,
      atlasScore: 90,
    ),
    PriceObservation(
      id: 'marjane-chicken-marrakech',
      itemName: 'Marjane Chicken',
      category: PriceIntelligenceCategory.supermarkets,
      cityName: 'Marrakech',
      district: 'Gueliz',
      unitLabel: 'kg',
      currentAmountMad: 68,
      minAmountMad: 62,
      avgAmountMad: 67,
      maxAmountMad: 75,
      lastUpdatedAt: updatedAt,
      source: 'Relevé supermarché (test)',
      confidence: PriceConfidence.medium,
      verificationStatus: PriceVerificationStatus.verified,
      userReportsCount: 1,
      atlasScore: 70,
    ),
    PriceObservation(
      id: 'taxi-airport-marrakech',
      itemName: 'Taxi Airport Marrakech',
      category: PriceIntelligenceCategory.taxi,
      cityName: 'Marrakech',
      unitLabel: 'trajet aéroport–centre',
      currentAmountMad: 80,
      minAmountMad: 70,
      avgAmountMad: 80,
      maxAmountMad: 100,
      lastUpdatedAt: updatedAt,
      source: 'Grille indicative vérifiée (test)',
      confidence: PriceConfidence.high,
      verificationStatus: PriceVerificationStatus.verified,
      userReportsCount: 5,
      atlasScore: 85,
    ),
    PriceObservation(
      id: 'cafe-noir-casablanca',
      itemName: 'Café noir',
      category: PriceIntelligenceCategory.coffee,
      cityName: 'Casablanca',
      unitLabel: 'tasse',
      currentAmountMad: 12,
      minAmountMad: 8,
      avgAmountMad: 12,
      maxAmountMad: 18,
      lastUpdatedAt: updatedAt,
      source: 'Relevé café (test)',
      confidence: PriceConfidence.medium,
      verificationStatus: PriceVerificationStatus.verified,
      atlasScore: 60,
    ),
  ];
}
