-- =============================================================================
-- 00019 — Prices Wave 2: Marrakech culture tickets (verified primary sources)
-- Additive. Do NOT invent prices.
-- Captured 2026-08-12: Ministère de la Culture e-services, Médersa Ben Youssef,
-- FNM Dar El Bacha, Maison de la Photographie, MACAAL, tickets.jardinmajorelle.com
-- (Majorelle / YSL admission + Moroccan/resident differentials).
-- No taxi / urban bus / parking — evidence insufficient.
-- =============================================================================

BEGIN;

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-palais-bahia-adulte-etranger-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'Palais Bahia — entrée adulte étranger',
  'par personne',
  100.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · Ministère de la Culture — e-services Palais Bahia',
  'https://e-services.minculture.gov.ma/fr/tickets/palais-bahia',
  'high',
  'verified',
  0,
  96,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-palais-bahia-adulte-marocain-resident-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'Palais Bahia — entrée adulte Marocain / résident',
  'par personne',
  30.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · Ministère de la Culture — e-services Palais Bahia',
  'https://e-services.minculture.gov.ma/fr/tickets/palais-bahia',
  'high',
  'verified',
  0,
  94,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-palais-el-badi-adulte-etranger-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'Palais El Badi — entrée adulte étranger',
  'par personne',
  100.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · Ministère de la Culture — e-services Palais Badii',
  'https://e-services.minculture.gov.ma/fr/tickets/palais-badii',
  'high',
  'verified',
  0,
  95,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-palais-el-badi-adulte-marocain-resident-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'Palais El Badi — entrée adulte Marocain / résident',
  'par personne',
  30.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · Ministère de la Culture — e-services Palais Badii',
  'https://e-services.minculture.gov.ma/fr/tickets/palais-badii',
  'high',
  'verified',
  0,
  93,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-tombeaux-saadiens-adulte-etranger-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'Tombeaux Saadiens — entrée adulte étranger',
  'par personne',
  100.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · Ministère de la Culture — e-services Tombeaux Saadiens',
  'https://e-services.minculture.gov.ma/fr/tickets/tombeaux-saadiens',
  'high',
  'verified',
  0,
  95,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-tombeaux-saadiens-adulte-marocain-resident-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'Tombeaux Saadiens — entrée adulte Marocain / résident',
  'par personne',
  30.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · Ministère de la Culture — e-services Tombeaux Saadiens',
  'https://e-services.minculture.gov.ma/fr/tickets/tombeaux-saadiens',
  'high',
  'verified',
  0,
  93,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-medersa-ben-youssef-adulte-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'Médersa Ben Youssef — entrée adulte',
  'par personne',
  50.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · Médersa Ben Youssef — site officiel (Tarifs)',
  'https://www.medersabenyoussef.ma/',
  'high',
  'verified',
  0,
  94,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-dar-el-bacha-adulte-etranger-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'Dar El Bacha — entrée étranger',
  'par personne',
  60.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · Fondation Nationale des Musées — Dar El Bacha',
  'https://fnm.ma/museums/26',
  'high',
  'verified',
  0,
  94,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-dar-el-bacha-adulte-marocain-resident-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'Dar El Bacha — entrée Marocain / résident',
  'par personne',
  25.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · Fondation Nationale des Musées — Dar El Bacha',
  'https://fnm.ma/museums/26',
  'high',
  'verified',
  0,
  92,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-maison-photographie-adulte-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'Maison de la Photographie — entrée adulte',
  'par personne',
  80.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · Maison de la Photographie — Horaires et tarifs',
  'https://maisondelaphotographie.ma/about/',
  'high',
  'verified',
  0,
  93,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-maison-photographie-resident-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'Maison de la Photographie — entrée résident',
  'par personne',
  50.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · Maison de la Photographie — Horaires et tarifs',
  'https://maisondelaphotographie.ma/about/',
  'high',
  'verified',
  0,
  91,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-macaal-adulte-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'MACAAL — entrée adulte',
  'par personne',
  120.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · MACAAL — Informations pratiques',
  'https://macaal.org/informations-pratiques',
  'high',
  'verified',
  0,
  95,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-macaal-resident-africain-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'MACAAL — entrée résident / nationalité africaine',
  'par personne',
  60.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · MACAAL — Informations pratiques',
  'https://macaal.org/informations-pratiques',
  'high',
  'verified',
  0,
  93,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-jardin-majorelle-admission-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'Jardin Majorelle — droit d''entrée',
  'par personne',
  170.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · Billetterie officielle Jardin Majorelle',
  'https://tickets.jardinmajorelle.com/visite',
  'high',
  'verified',
  0,
  97,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-jardin-majorelle-marocain-resident-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'Jardin Majorelle — citoyens marocains / résidents étrangers',
  'par personne',
  75.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · Billetterie officielle Jardin Majorelle',
  'https://tickets.jardinmajorelle.com/visite',
  'high',
  'verified',
  0,
  95,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-musee-ysl-admission-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'Musée Yves Saint Laurent — droit d''entrée',
  'par personne',
  140.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · Billetterie officielle Jardin Majorelle (Musée YSL)',
  'https://tickets.jardinmajorelle.com/visite',
  'high',
  'verified',
  0,
  96,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

INSERT INTO price_observations (
  slug, category, city_name, district, item_name, unit_label,
  current_amount_mad, min_amount_mad, avg_amount_mad, max_amount_mad,
  currency, last_updated_at, source, source_url, confidence,
  verification_status, user_reports_count, atlas_score, is_published
) VALUES (
  'culture-musee-ysl-marocain-resident-marrakech',
  'culture',
  'Marrakech',
  NULL,
  'Musée Yves Saint Laurent — citoyens marocains / résidents étrangers',
  'par personne',
  55.0,
  NULL,
  NULL,
  NULL,
  'MAD',
  '2026-08-12T00:00:00.000Z',
  'official_operator · Billetterie officielle Jardin Majorelle (Musée YSL)',
  'https://tickets.jardinmajorelle.com/visite',
  'high',
  'verified',
  0,
  94,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  city_name = EXCLUDED.city_name,
  district = EXCLUDED.district,
  item_name = EXCLUDED.item_name,
  unit_label = EXCLUDED.unit_label,
  current_amount_mad = EXCLUDED.current_amount_mad,
  min_amount_mad = EXCLUDED.min_amount_mad,
  avg_amount_mad = EXCLUDED.avg_amount_mad,
  max_amount_mad = EXCLUDED.max_amount_mad,
  currency = EXCLUDED.currency,
  last_updated_at = EXCLUDED.last_updated_at,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  confidence = EXCLUDED.confidence,
  verification_status = EXCLUDED.verification_status,
  atlas_score = EXCLUDED.atlas_score,
  is_published = EXCLUDED.is_published,
  updated_at = now();

COMMIT;
